### Retrieves an authentication token.
POST {{apiUrl}}/auth/oauth/v2/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{$processEnv DELL_CLIENT_ID}}
&client_secret={{$processEnv DELL_CLIENT_SECRET}}
