@poNumber = <po-number>

###

// Retrieves order status information.
POST {{baseUrl}}/PROD/order-status/api/search
Accept: application/json
Accepts-Version: 2.0
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
	"searchParameter": [
		{
			"key": "po_numbers",
			"values": ["{{poNumber}}"]
		}
	]
}
