@locale = fr-FR
@quoteNumber = <quote-number>
@quoteVersion = <quote-version>

###

// Gets quote information by number, version and locale.
GET {{baseUrl}}/PROD/QuoteSearchApi/api/v1/quote/{{quoteNumber}}/{{quoteVersion}}/{{locale}}
Accept: application/json
Authorization: Bearer {{accessToken}}
